import type { Metadata } from 'next';
import { M_PLUS_1 } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const m1Plus = M_PLUS_1({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          m1Plus.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
