import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { m1PlusRounded } from '@/components/fonts';
import { Navbar } from '@/components/Navbar';
import { ThemeProvider } from '@/components/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // NOTE: There could be another way to preve missmatching between cliente and server renders
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          m1PlusRounded.variable,
          'min-h-screen bg-background font-sans antialiased',
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
